import { parseUnits } from 'viem'

export const FACTORY_ADDRESS = '0x3E4c189Aca6600d33E7a100bf9dB4bB44827299B' as const
export const USDC_ADDRESS = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' as const
export const ARBITRATOR_ADDRESS = '0xdA5043637A9505A9daA85c86fEE7D8D463307698' as const

export const factoryAbi = [
    {
        type: 'function',
        name: 'allEscrows',
        inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'allowedTokens',
        inputs: [{ name: '', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'arbiterFeeBps',
        inputs: [],
        outputs: [{ name: '', type: 'uint16', internalType: 'uint16' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'buyerEscrows',
        inputs: [
            { name: '', type: 'address', internalType: 'address' },
            { name: '', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'createEscrow',
        inputs: [
            { name: 'seller', type: 'address', internalType: 'address' },
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'amount', type: 'uint256', internalType: 'uint256' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
            { name: 'arbiter', type: 'address', internalType: 'address' },
            { name: 'memoHash', type: 'bytes32', internalType: 'bytes32' },
        ],
        outputs: [{ name: 'escrowAddress', type: 'address', internalType: 'address' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'defaultPoolFee',
        inputs: [],
        outputs: [{ name: '', type: 'uint24', internalType: 'uint24' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'feeToken',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getBuyerEscrows',
        inputs: [{ name: '_buyer', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getEscrowById',
        inputs: [{ name: 'id', type: 'uint256', internalType: 'uint256' }],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getEscrowCount',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getSellerEscrows',
        inputs: [{ name: '_seller', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'owner',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'sellerEscrows',
        inputs: [
            { name: '', type: 'address', internalType: 'address' },
            { name: '', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'setArbiterFeeBps',
        inputs: [{ name: '_bps', type: 'uint16', internalType: 'uint16' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'setDefaultPoolFee',
        inputs: [{ name: '_fee', type: 'uint24', internalType: 'uint24' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'setFeeToken',
        inputs: [{ name: '_token', type: 'address', internalType: 'address' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'setSwapRouter',
        inputs: [{ name: '_router', type: 'address', internalType: 'address' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'setTokenAllowed',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'allowed', type: 'bool', internalType: 'bool' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'swapRouter',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'transferOwnership',
        inputs: [{ name: '_newOwner', type: 'address', internalType: 'address' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'event',
        name: 'CalconfigUpdated',
        inputs: [
            { name: 'key', type: 'string', indexed: false, internalType: 'string' },
            { name: 'value', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'ConfigUpdated',
        inputs: [
            { name: 'key', type: 'string', indexed: false, internalType: 'string' },
            { name: 'value', type: 'address', indexed: false, internalType: 'address' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'EscrowCreated',
        inputs: [
            { name: 'escrowAddress', type: 'address', indexed: true, internalType: 'address' },
            { name: 'escrowId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'buyer', type: 'address', indexed: true, internalType: 'address' },
            { name: 'seller', type: 'address', indexed: false, internalType: 'address' },
            { name: 'token', type: 'address', indexed: false, internalType: 'address' },
            { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'deadline', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'arbiter', type: 'address', indexed: false, internalType: 'address' },
            { name: 'memoHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'TokenAllowed',
        inputs: [
            { name: 'token', type: 'address', indexed: true, internalType: 'address' },
            { name: 'allowed', type: 'bool', indexed: false, internalType: 'bool' },
        ],
        anonymous: false,
    },
] as const

export const escrowAbi = [
    {
        type: 'function',
        name: 'amount',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'arbiter',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'arbiterFeeBps',
        inputs: [],
        outputs: [{ name: '', type: 'uint16', internalType: 'uint16' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'buyer',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'deadline',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'feeToken',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'fund',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'fundedAt',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getDealInfo',
        inputs: [],
        outputs: [
            { name: '_buyer', type: 'address', internalType: 'address' },
            { name: '_seller', type: 'address', internalType: 'address' },
            { name: '_token', type: 'address', internalType: 'address' },
            { name: '_amount', type: 'uint256', internalType: 'uint256' },
            { name: '_deadline', type: 'uint256', internalType: 'uint256' },
            { name: '_arbiter', type: 'address', internalType: 'address' },
            { name: '_memoHash', type: 'bytes32', internalType: 'bytes32' },
            { name: '_status', type: 'uint8', internalType: 'enum Escrow.Status' },
            { name: '_fundedAt', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'memoHash',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'openDispute',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'poolFee',
        inputs: [],
        outputs: [{ name: '', type: 'uint24', internalType: 'uint24' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'refundAfterDeadline',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'release',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'resolve',
        inputs: [{ name: '_payToSeller', type: 'bool', internalType: 'bool' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'seller',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'status',
        inputs: [],
        outputs: [{ name: '', type: 'uint8', internalType: 'enum Escrow.Status' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'swapRouter',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'token',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'event',
        name: 'DisputeOpened',
        inputs: [
            { name: 'initiator', type: 'address', indexed: true, internalType: 'address' },
            { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'DisputeResolved',
        inputs: [
            { name: 'winner', type: 'address', indexed: true, internalType: 'address' },
            { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'FeePaid',
        inputs: [
            { name: 'arbiter', type: 'address', indexed: true, internalType: 'address' },
            { name: 'usdcAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'townsAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Funded',
        inputs: [
            { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Refunded',
        inputs: [
            { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Released',
        inputs: [
            { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
] as const

export const erc20Abi = [
    {
        type: 'function',
        name: 'approve',
        inputs: [
            { name: 'spender', type: 'address' },
            { name: 'amount', type: 'uint256' },
        ],
        outputs: [{ name: '', type: 'bool' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'allowance',
        inputs: [
            { name: 'owner', type: 'address' },
            { name: 'spender', type: 'address' },
        ],
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'balanceOf',
        inputs: [{ name: 'account', type: 'address' }],
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
    },
] as const

export function parseUsdcAmount(amount: string | number): bigint {
    return parseUnits(String(amount), 6)
}
